// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBetp1TcWXgXumXZJwaAMH1k23BMUCTwBg',
    appId: '1:311897494492:web:89166d1339844a49b7f519',
    messagingSenderId: '311897494492',
    projectId: 'assetflow-7a811',
    authDomain: 'assetflow-7a811.firebaseapp.com',
    storageBucket: 'assetflow-7a811.firebasestorage.app',
    measurementId: 'G-ZD6038RJ63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE9cZwbhlzsW6cxhJocc9TtTliEt4-PEE',
    appId: '1:311897494492:android:e9294749c82158b4b7f519',
    messagingSenderId: '311897494492',
    projectId: 'assetflow-7a811',
    storageBucket: 'assetflow-7a811.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEuI6Xxg6ExOSxltfx6wl30j1jgFv9pCg',
    appId: '1:311897494492:ios:e6a066f096af13fbb7f519',
    messagingSenderId: '311897494492',
    projectId: 'assetflow-7a811',
    storageBucket: 'assetflow-7a811.firebasestorage.app',
    iosBundleId: 'com.example.assetdashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEuI6Xxg6ExOSxltfx6wl30j1jgFv9pCg',
    appId: '1:311897494492:ios:e6a066f096af13fbb7f519',
    messagingSenderId: '311897494492',
    projectId: 'assetflow-7a811',
    storageBucket: 'assetflow-7a811.firebasestorage.app',
    iosBundleId: 'com.example.assetdashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBetp1TcWXgXumXZJwaAMH1k23BMUCTwBg',
    appId: '1:311897494492:web:610a8099707c6cb1b7f519',
    messagingSenderId: '311897494492',
    projectId: 'assetflow-7a811',
    authDomain: 'assetflow-7a811.firebaseapp.com',
    storageBucket: 'assetflow-7a811.firebasestorage.app',
    measurementId: 'G-3N5N92P6NK',
  );
}
